mongo:
  address:    "127.0.0.1:27017"
  db:         "initialiser_db"
  collection: "running_services"
kafka:
  address: ["52.172.89.249:9092"]



# {"ip": "20.219.73.70", "port": "5005", "name": "deployer", "type": "service"}
# {"ip": "20.219.73.70", "port": "5000", "name": "node-manager", "type": "service"}
# {"ip": "20.219.73.70", "port": "5001", "name": "node-agent1", "type": "node-agent"}
# {"ip": "20.219.73.70", "port": "5004", "name": "scheduler", "type": "service"}